### ISSUE TITLE
Bug: can't import, and can't compile

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [lawloretienne/Loop#1]
When importing via Android-Studio, it failed, and even when using TurtoiseGit and then import, I got an issue with gradle about this line:

manifestPlaceholders = [fabricApiKey: FABRIC_API_KEY]

So when I removed it, I got this error:

D:\android\Android studio Projects\Loop\app\src\main\AndroidManifest.xml:21:13-44 Error:
    Attribute meta-data#io.fabric.ApiKey@value at AndroidManifest.xml:21:13-44 requires a placeholder substitution but no value for <fabricApiKey> is provided.
D:\android\Android studio Projects\Loop\app\src\main\AndroidManifest.xml Error:
    Validation failed, exiting
Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed with multiple errors, see logs

so I removed the metadata on the manifest:

```
    <meta-data
        android:name="io.fabric.ApiKey"
        android:value="${fabricApiKey}" />
```

And then I got this huge error:

ERROR - Crashlytics Developer Tools error.
java.lang.IllegalArgumentException: Crashlytics found an invalid API key: null. 
Check the Crashlytics plugin to make sure that the application has been added successfully! 
Contact support@fabric.io for assistance.
    at com.crashlytics.tools.android.DeveloperTools.processApiKey(DeveloperTools.java:326)
    at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:466)
    at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
    at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
    at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at com.crashlytics.tools.gradle.tasks.FabricTaskBuilder.callDevtoolsWrappingRuntimeExceptions(FabricTaskBuilder.groovy:313)
    at com.crashlytics.tools.gradle.tasks.FabricTaskBuilder.this$2$callDevtoolsWrappingRuntimeExceptions(FabricTaskBuilder.groovy)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:368)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
    at com.crashlytics.tools.gradle.tasks.FabricTaskBuilder$_pluginGenerateResources_closure3.doCall(FabricTaskBuilder.groovy:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
    at groovy.lang.Closure.call(Closure.java:423)
    at groovy.lang.Closure.call(Closure.java:439)
    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:548)
    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:529)
    at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
    at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:43)
    at org.gradle.tooling.internal.provider.BuildModelAction.run(BuildModelAction.java:30)
    at org.gradle.tooling.internal.provider.ConfiguringBuildAction.run(ConfiguringBuildAction.java:119)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
    at org.gradle.util.Swapper.swap(Swapper.java:38)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
    at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
    at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
:app:fabricGenerateResourcesDebug FAILED
Error:Execution failed for task ':app:fabricGenerateResourcesDebug'.

> Crashlytics Developer Tools error.

**Comment by lawloretienne** [comment]
Do you have a Fabric account (https://fabric.io)? If so then copy that api key and add this to the gradle.properties folder at the root of your project like so

FABRIC_API_KEY=XXXXXXXXXXXXXXXXXXXXX

I didn't check this file into git since its sensitive info.

**Comment by AndroidDeveloperLB** [comment]
no, but why close the issue? Did you fix it?

**Comment by lawloretienne** [comment]
okay i reopened the issue.  I didnt fix anything.  I intentionally made that api key private since it is sensitive info.  You can very easily swap in your own api key from Fabric.

**Comment by Orinameh** [comment]
Where do I get my the fabric key? Do I still need to download anything from fabric?

**Comment by Orinameh** [comment]
Still can't compile the app...I am getting error and android studio is not recognizing the folder as an android project. Any thought?

**Comment by lawloretienne** [comment]
@Orinameh have you set up an account at Fabric.io ?

**Comment by Orinameh** [comment]
@lawloretienne Yes I have. I cloned the master branch but it is not being detected as an android project by android studio. Even when I installed the fabric puglin in android studio, it is not recognizing the project. I really need this to learn a skill or two from you

**Comment by lawloretienne** [comment]
Can you tell me what errors are showing up in Android Studio?

**Comment by AlienAsRoger** [comment]
I guess that instead of error during the project compilation or error, you would throw an Exception on project run if deafult API key is not set. I.e. I'd like to look into the code though IDE, but I can't even compile the project w/o additional steps that I don't want to make though :)

**Comment by lawloretienne** [comment]
What is the latest error that you are getting?  I guess I dont know how far along you are in the setup.

**Comment by AndroidDeveloperLB** [comment]
Why close it again? This project cannot be opened...

This is the latest error:
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

I had to perform these changes for it to build well:

        classpath 'com.android.tools.build:gradle:2.2.2'
        classpath 'io.fabric.tools:gradle:1.22.0'


    compileSdkVersion 25
    buildToolsVersion '23.0.3'

    defaultConfig {
        applicationId "com.etiennelawlor.loop"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
//        manifestPlaceholders = [fabricApiKey: FABRIC_API_KEY]
    }



    compile 'com.google.android.gms:play-services-base:9.6.1'
    compile 'com.android.support:design:25.0.0'
    compile 'com.android.support:support-v4:25.0.0'
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.android.support:cardview-v7:25.0.0'
    compile 'com.android.support:recyclerview-v7:25.0.0'
    compile 'com.android.support:palette-v7:25.0.0'

**Comment by lawloretienne** [comment]
So I have made several updates to this repo.  Is this still an issue @AndroidDeveloperLB?

**Comment by AndroidDeveloperLB** [comment]
Yes, I get this error:
Error:(14, 0) Could not get unknown property 'FABRIC_API_KEY' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=16, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=25, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=1.0, applicationId=com.etiennelawlor.loop, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
<a href="openFile:D:\android\Android studio Projects\Loop\app\build.gradle">Open File</a>

**Comment by lawloretienne** [comment]
@AndroidDeveloperLB Do you have a Fabric API KEY?  I Have one that is set up in my gradle.properties file that is not checked into the repo.

**Comment by AndroidDeveloperLB** [comment]
Why do we have to put it in a sample?

**Comment by lawloretienne** [comment]
I am showcasing using Fabric for Analytics.  If you don't want any of that stuff then you should be able to comment all code relating to Fabric.

**Comment by ankushmittal-milestone** [comment]
Help me to resolve this error 

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by lawloretienne** [comment]
@ankushmittal-milestone can you give me some more context?  Have you set up a Fabric API KEY?

**Comment by lawloretienne** [comment]
I have commented out Fabric related code.  You should now be able to run the project without making any changes.  Closing this for now.  Re-open if there are still issues.

**Comment by AndroidDeveloperLB** [comment]
Thank you.
You could just make it optional instead.
Anyway, I still see these issues:

D:\Desktop\Loop\app\src\main\java\com\etiennelawlor\loop\activities\LoginActivity.java
Error:(170, 35) error: cannot find symbol variable client_id
Error:(171, 35) error: cannot find symbol variable client_secret
Error:(197, 53) error: cannot find symbol variable client_id
D:\Desktop\Loop\app\src\main\java\com\etiennelawlor\loop\LoopApplication.java
Error:(105, 50) error: cannot find symbol variable flurry_api_key

**Comment by lawloretienne** [comment]
So again those are other confidential keys that i have not checked into the repo.

client_id and client_secret are both from a registered Vimeo app.  You will need to register an application to obtain these.

flurry_api_key is the API key coming from a registered Flurry app.  You will also need to register a flurry application to obtain this.  

At this point I am not trying to comment all of these out since the app won't even run.

**Comment by AndroidDeveloperLB** [comment]
ok, then, can you provide an APK so that we could see what this library is
capable of, because the sample cannot compile without registration.

**Comment by lawloretienne** [comment]
So you are not trying to register an application.  Would you like the links to these pages?

**Comment by AndroidDeveloperLB** [comment]
I just wanted to try the sample, to see how good the library is.

**Comment by lawloretienne** [comment]
Hey @AndroidDeveloperLB so now you can try out the sample.  Check out the APK in Releases
https://github.com/lawloretienne/Loop/releases

**Comment by AndroidDeveloperLB** [comment]
Seems like it needs the user to login as well. This seems odd, because
everyone can access Vimeo website without the need to login.
Anyway, thanks.

**Comment by lawloretienne** [comment]
So my sample app will let you access your liked videos, videos you have added to the watch later queue, and allow you to like and add videos to the watch later queue. you need to be an authenticated user to have access to all of these things.

**Comment by AndroidDeveloperLB** [comment]
I see. Thanks.
